### PR TITLE
Add installation notes

### PR DESCRIPTION
**Pull request by edwardtheharris**
@edwardtheharris

Changelog: changed

### CODE REVIEW

**Comment by Freed-Wu** [comment]
What is the difference from <https://sphinxcontrib-eval.readthedocs.io/en/latest/resources/install.html>?

And they are documented in <https://github.com/sphinx-contrib/eval/blob/main/docs/resources/install.md>, not `README.md`.

**Comment by edwardtheharris** [comment]
> What is the difference from https://sphinxcontrib-eval.readthedocs.io/en/latest/resources/install.html?
> 
> And they are documented in https://github.com/sphinx-contrib/eval/blob/main/docs/resources/install.md, not `README.md`.

Oh, that's helpful because I was unable to find them after an admittedly brief search. This kind of thing is exactly what the readme file is intended for, is it not?

**Comment by Freed-Wu** [comment]
Or we can add a link to install.md in README.md?

**Comment by Freed-Wu** [comment]
Currently, I only package it to PYPI and AUR. However, a python package can be packaged to many platforms: Nix NUR, Conda, Homebrew, Ubuntu PPA, Gentoo Overlay ... It can be a very long list. So I specially create a standalone markdown file to recode install methods.

**Comment by edwardtheharris** [comment]
> Or we can add a link to install.md in README.md?

That'd make exactly the sort of admittedly brief review of the readme that I did provide just the information I was aiming to provide with this update. I can update the PR if you like.

**Pull request merged**
